apiVersion: 1

groups:
  - orgId: 1
    name: –ú–∏—è–ª–Ω–∞ webhook
    folder: Webhook Alerting
    interval: 5m
    rules:
      - uid: webhook-rAc7STtVk
        title: –ú–∏—è–ª–Ω–∞ (Webhook)
        condition: C
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 3600
              to: 1800
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: dishwasher
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 1800
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: dishwasher
          - refId: C
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [10]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: max
                - evaluator:
                    params: [10]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [B]
                  reducer:
                    type: max
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: NoData
        execErrState: OK
        for: 0s
        annotations:
          __alertId__: "3"
          __dashboardUid__: "reminders"
          __panelId__: "1"
          message: "üçΩÔ∏è –ò–∑–≤–µ—Å—Ç–∏–µ –∑–∞ –º–∏—è–ª–Ω–∞—Ç–∞: –ú–∏—è–ª–Ω–∞—Ç–∞ –µ –≥–æ—Ç–æ–≤–∞"
          summary: "–ù–∞–ø–æ–º–Ω—è–Ω–µ –∑–∞ –º–∏—è–ª–Ω–∞"
          description: "–ú–∏—è–ª–Ω–∞—Ç–∞ –∑–∞–≤—ä—Ä—à–∏ –ø—Ä–æ–≥—Ä–∞–º–∞—Ç–∞ —Å–∏ - –∫–æ–Ω—Å—É–º–∞—Ü–∏—è—Ç–∞ —Å–ø–∞–¥–Ω–∞ –ø–æ–¥ 10W. –ú–æ–∂–µ—Ç–µ –¥–∞ –∏–∑–≤–∞–∂–∏—Ç–µ —á–∏—Å—Ç–∏—Ç–µ —Å—ä–¥–æ–≤–µ."
        labels:
          rule_uid: webhook-rAc7STtVk
          alert_type: webhook