apiVersion: 1

groups:
  - orgId: 1
    name: Термопомпа webhook
    folder: Webhook Alerting
    interval: 1m
    rules:
      - uid: webhook-3A5nIop4k
        title: Термопомпа не работи (Webhook)
        condition: A
        data:
          - refId: power
            queryType: ''
            relativeTimeRange:
              from: 120
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: heat_pump
                - condition: AND
                  key: phase
                  operator: "="
                  value: B
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [30, 3000]
                    type: lt
                  operator:
                    type: and
                  query:
                    params: [power]
                  reducer:
                    type: avg
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: NoData
        execErrState: OK
        for: 15m
        annotations:
          __alertId__: "11"
          __dashboardUid__: "Nml0-Fonz"
          __panelId__: "2"
          message: "Консумация под 29W"
        labels:
          rule_uid: webhook-3A5nIop4k
          alert_type: webhook
      - uid: webhook-lA5nSTt4k
        title: Термопомпа претоварване (Webhook)
        condition: B
        data:
          - refId: A
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: P3C6603E967DC8568
            model:
              groupBy:
                - params: ["$__interval"]
                  type: time
                - params: ["null"]
                  type: fill
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: current_power
              orderByTime: ASC
              policy: default
              resultFormat: time_series
              select:
                - - params: ["p"]
                    type: field
                  - params: []
                    type: max
              tags:
                - key: "device.name"
                  operator: "="
                  value: heat_pump
          - refId: B
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: __expr__
            model:
              datasource:
                type: __expr__
                uid: __expr__
              conditions:
                - evaluator:
                    params: [3000]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    type: avg
              intervalMs: 1000
              maxDataPoints: 43200
              type: classic_conditions
        noDataState: NoData
        execErrState: OK
        for: 10m
        annotations:
          __alertId__: "13"
          __dashboardUid__: "Nml0-Fonz"
          __panelId__: "2"
          message: "Консумация над 3kW"
        labels:
          rule_uid: webhook-lA5nSTt4k
          alert_type: webhook